### ISSUE TITLE
invalid base64 

### ISSUE THREAD

**Issue by roman-kiselenko** [miyucy/web_push#1]
`invalid base64` error raised if sended to firefox.

**Comment by miyucy** [comment]
thanks for notify to me. I will check it.

**Comment by miyucy** [comment]
Hmm, it's working on fx 50.1.0.
<img width="463" alt="2017-01-18 1 32 34" src="https://cloud.githubusercontent.com/assets/51594/22029469/05c96b96-dd1e-11e6-9066-0a0510494ba5.png">

I was tested with below scripts:

```ruby
subscription = JSON.parse <<JSON, symbolize_names: true
{
  "endpoint": "https://updates.push.services.mozilla.com/wpush/v2/xxx",
  "keys": {
    "auth": "xxx",
    "p256dh": "xxx"
  }
}
JSON

wp = WebPush.new subscription
wp.set_vapid_details('mailto:fistfvck@gmail.com',
                     'BFn00OL-Fb56exz43l-THJHCbyP8K8bXDC7HzUOdkphCz7whsESosWRK4sLYcr4CX1OMCxxJF0P7U34oJGDhFnc',
                     'xxx')
wp.send_notification(
  {
    title: "LGTM",
    body: "L G T M",
    icon: "https://pbs.twimg.com/media/CQCg9EGUYAAMBJy.jpg"
  }.to_json
)
```

subscription get from https://miyucy.github.io/push.html.

**Comment by roman-kiselenko** [comment]
@miyucy ok, I'll try it. Thanks for a quick response. 

The steps to reproduce:

```ruby
# Generate a keys and puts it to Rails.application.secrets.web_push_public_key
pkey = WebPush::Utils.generate_vapid_pkey
# Rails.application.secrets.web_push_private_key
vapid_private_key = Base64.urlsafe_encode64(pkey.private_key.to_bn.to_s(2)).delete('=')
# Rails.application.secrets.web_push_public_key
vapid_public_key = Base64.urlsafe_encode64(pkey.public_key.to_bn.to_s(2)).delete('=')
```
Puts a public key to view(for `sub.js` script)
![1484675863](https://cloud.githubusercontent.com/assets/3471384/22033066/0f0d9e96-dcf8-11e6-9680-e9ab3884e81d.png)

subscription.js
https://github.com/miyucy/miyucy.github.io/blob/master/push.js#L1

Send web push from Rails app
![1484675960](https://cloud.githubusercontent.com/assets/3471384/22033126/530db0c2-dcf8-11e6-912a-8ef4bd246dca.png)

Note about `=` at the end, in other case it is not working for some reason.

`set_vapid_details(...)` - works fine with chrome, but it's raise an exception if reciever is firefox.

![1484676101](https://cloud.githubusercontent.com/assets/3471384/22033229/b70308d4-dcf8-11e6-97db-306f6fc5c9bb.png)


@miyucy Could you please check it, maybe I missing something?

**Comment by miyucy** [comment]
> Note about = at the end, in other case it is not working for some reason.

Maybe caused by this.

https://gist.github.com/miyucy/ac33be67ff42b2ad0da9356079bf329b#file-push-rb-L13-L15
Could you check out this gist. and run your local PC. Is this working?

**Comment by roman-kiselenko** [comment]
@miyucy 

Still the same error.

Maybe it is matter I'm using ruby `2.2.5`

![1484823114](https://cloud.githubusercontent.com/assets/3471384/22104141/f6d50636-de4e-11e6-835b-07857a9f0026.png)

**Comment by miyucy** [comment]
ah.. im using 2.3.3

**Comment by miyucy** [comment]
i wil test with 2.2

**Comment by roman-kiselenko** [comment]
@miyucy I tested, it is works with ruby 2.3.3  in the Chrome and Firefox 

Open a PR #2 for notice other users. That's issue can be closed. Thanks for your help. :+1:

**Comment by miyucy** [comment]
I did fix this bug. `Base64.urlsafe_encode64` behavior was changing.

```ruby
--- /Users/miyucy/.rbenv/versions/2.2.0/lib/ruby/2.2.0/base64.rb	2013-05-19 12:10:21.000000000 +0900
+++ /Users/miyucy/.rbenv/versions/2.3.3/lib/ruby/2.3.0/base64.rb	2015-12-16 14:07:31.000000000 +0900
@@ -1,3 +1,4 @@
+# frozen_string_literal: false
 #
 # = base64.rb: methods for base64-encoding and -decoding strings
 #
@@ -77,15 +78,30 @@
   # This method complies with ``Base 64 Encoding with URL and Filename Safe
   # Alphabet'' in RFC 4648.
   # The alphabet uses '-' instead of '+' and '_' instead of '/'.
-  def urlsafe_encode64(bin)
-    strict_encode64(bin).tr("+/", "-_")
+  # Note that the result can still contain '='.
+  # You can remove the padding by setting +padding+ as false.
+  def urlsafe_encode64(bin, padding: true)
+    str = strict_encode64(bin).tr("+/", "-_")
+    str = str.delete("=") unless padding
+    str
   end
 
   # Returns the Base64-decoded version of +str+.
   # This method complies with ``Base 64 Encoding with URL and Filename Safe
   # Alphabet'' in RFC 4648.
   # The alphabet uses '-' instead of '+' and '_' instead of '/'.
+  #
+  # The padding character is optional.
+  # This method accepts both correctly-padded and unpadded input.
+  # Note that it still rejects incorrectly-padded input.
   def urlsafe_decode64(str)
-    strict_decode64(str.tr("-_", "+/"))
+    # NOTE: RFC 4648 does say nothing about unpadded input, but says that
+    # "the excess pad characters MAY also be ignored", so it is inferred that
+    # unpadded input is also acceptable.
+    str = str.tr("-_", "+/")
+    if !str.end_with?("=") && str.length % 4 != 0
+      str = str.ljust((str.length + 3) & ~3, "=")
+    end
+    strict_decode64(str)
   end
 end
```

**Comment by miyucy** [comment]
So, now. It will be working on 2.2.x too. I tested on ruby-v2.2.0. 🎉
